development:
  app_key: "l2xp3zvncqotdzz"
  app_secret: "i8i3pbpjv7mm5gi"
  access_token: "x25r4uexhvuprg3u"
  access_token_secret: "rh4zy196h4qgla4"
  user_id: "85990052"
  access_type: "dropbox"
production:
  app_key: "l2xp3zvncqotdzz"
  app_secret: "i8i3pbpjv7mm5gi"
  access_token: "qb4hw6i7t4p9e2av"
  access_token_secret: "fbms6sz9p1yo6b4"
  user_id: "85990052"
  access_type: "dropbox"